In [1]:
import numpy as np

In [3]:
my_array = np.arange(10000)

In [4]:
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
%time my_array = np.arange(10000)

Wall time: 0 ns


In [10]:
data = np.random.randn(2,3)

In [11]:
data

array([[-0.10095601,  0.28418387, -0.69049989],
       [-1.29018856, -0.40435094, -0.83120044]])

In [13]:
data = np.random.randn(10,10)

In [15]:
data

array([[-1.18618661e-01, -2.01715686e+00, -6.22769175e-01,
        -4.60450653e-01, -1.32327748e+00, -1.13674473e+00,
         1.56929506e+00, -5.32484390e-01,  8.67067542e-01,
         4.03156471e-01],
       [-2.15136186e+00,  2.10953336e-01,  3.33980526e-01,
         7.64575203e-01, -5.31517473e-01, -1.25287387e-03,
         1.59021835e+00,  6.24954706e-01,  5.75611737e-01,
         1.04617057e+00],
       [-5.81940761e-01, -1.57399114e-01,  1.63261765e+00,
         8.57086184e-01, -7.39225645e-01,  6.84158800e-01,
         1.84460835e-01, -1.29078545e+00, -1.92242605e+00,
         1.22713110e+00],
       [ 3.86729903e-01,  1.77773342e-02, -6.41305501e-03,
         2.11420391e+00,  1.06376133e+00,  2.33705321e-01,
         4.86434227e-01, -2.44007119e+00, -2.83361474e-01,
        -3.20020017e-01],
       [-2.09237561e-01, -6.56763861e-02,  2.23792942e+00,
         4.37375401e-01, -1.06568946e-02,  2.62805928e+00,
        -1.28720664e+00,  8.32311257e-01,  6.44722826e-01,
         5.

In [16]:
data = np.random.randn(2,3)

In [18]:
data

array([[ 0.37642486,  0.34606693, -0.65995392],
       [-1.80897746, -0.87255092,  0.3194366 ]])

In [20]:
data + data

array([[ 0.75284972,  0.69213386, -1.31990785],
       [-3.61795492, -1.74510183,  0.6388732 ]])

In [22]:
data = np.random.randint(2,3)

In [23]:
data

2

In [29]:
data = np.random.randint(2, size = (2,3))

In [31]:
data

array([[0, 1, 1],
       [0, 0, 1]])

In [55]:
data / (np.random.randint(1, size = (2,3)))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf],
       [nan, nan, inf]])

In [56]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [59]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [61]:
arr1.dtype

dtype('float64')

In [63]:
arr2.dtype

dtype('int32')

In [65]:
arr1[0]

1.0

In [67]:
arr2[0]

1

In [68]:
arr1[0] + arr2[0]

2.0

In [70]:
arr1[0] = 10
arr1

array([10.,  2.,  3.])

In [72]:
arr2[0] = 10
arr2

array([10,  2,  3])

In [73]:
my_array = np.arange(36)

In [83]:
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
my_array = my_array.reshape(6,6)

In [81]:
my_array[0, 3:5]

array([3, 4])

In [84]:
my_array[4: , 4:]

array([[28, 29],
       [34, 35]])

In [89]:
my_array[0::2 , ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

"""
There are N bulbs, numbered from 1 to N, arranged in a row. The first bulb is plugged into the power socket and each successive bulb is connected to the previous one (the second bulb to the first, the third bulb to the second, etc.). (Wow, whoever wrote this doesn't know crap about wiring up lighting!)
Initially, all the bulbs are turned off. At moment K (for K from 0 to N−1), we turn on the A[K]-th bulb. A bulb shines if it is on and all the previous bulbs are turned on too. Write a function solution that, given an array A of N different integers from 1 to N, returns the number of moments for which every turned on bulb shines. Examples:
Given [2, 1, 3, 5, 4], the function should return 3.
At the 0th moment only the 2nd bulb is turned on, but it does not shine because the previous one is not on.
At the 1st moment two bulbs are turned on (1st and 2nd) and both of them shine.
At the 2nd moment three bulbs are turned on (1st, 2nd and 3rd) and all of them shine.
At the 3rd moment four bulbs are turned on (1st, 2nd, 3rd and 5th), but the 5th bulb does not shine because the previous one is not turned on.
At the 4th moment five bulbs are turned on (1st, 2nd, 3rd, 4th and 5th) and all five of them shine. There are three moments (1st, 2nd and 4th) when every turned on bulb shines.
More sample cases:
A=[2, 3, 4, 1, 5], the function should return 2 (at the 3rd and 4th moment every turned on bulb shines).
A=[1, 3, 4, 2, 5], the function should return 3 (at the 0th, 3rd and 4th moment every turned on bulb shines). Assume that:
Furtive validation criteria: N is an integer within the range [1..100]; the elements of A are all distinct; each element of array A is an integer within the range [1..N].
"""

In [167]:
A = np.array([2,1,3,5,4], dtype=np.int32)
A.dtype
A

array([2, 1, 3, 5, 4])

In [147]:
def lampadas(A):
    result = 0
    soma = 0
    for x in range(len(A)):
        soma += (x+1) 
        print(x, soma, sum(A[:x+1]), A[:x+1])
        if soma == sum(A[:x+1]):
            result += 1
    return result

lampadas(A)

0 1 2 [2]
1 3 3 [2 1]
2 6 6 [2 1 3]
3 10 11 [2 1 3 5]
4 15 15 [2 1 3 5 4]


3

In [153]:
A.size

5

In [161]:
index = np.cumsum(A)

In [164]:
teste = np.cumsum([1,2,3,4,5])

In [163]:
index

array([ 2,  3,  6, 11, 15], dtype=int32)

In [168]:
teste

array([ 1,  3,  6, 10, 15], dtype=int32)

In [170]:
sum(np.cumsum(index) = np.cumsum(teste))

SyntaxError: keyword can't be an expression (<ipython-input-170-4e3a05e2d443>, line 1)

Desafio #2

In [174]:
a = np.random.randint(10, size=(3,5))
a

array([[0, 4, 3, 0, 1],
       [8, 4, 1, 1, 6],
       [6, 8, 0, 7, 7]])

In [190]:
from collections import defaultdict

def conta(a):
    b = defaultdict(int)
    for x in a:
        for y in x:
            b[y] +=1
    return b

conta(a)



defaultdict(int, {0: 3, 4: 2, 3: 1, 1: 3, 8: 2, 6: 2, 7: 2})